# Generated by Django 3.0.6 on 2020-06-27 23:37

from django.db import migrations, models
import django.db.models.deletion
import evangelizacao.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voluntarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evangelizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('language', models.CharField(default='Portuguese', max_length=200)),
                ('class_date', models.DateTimeField(blank=True)),
                ('class_type', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('doc_file', models.FileField(upload_to="uploads/evangelizacao/%Y_%m_%d/'", validators=[evangelizacao.validators.validate_file_extension])),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='voluntarios.Voluntario')),
            ],
        ),
    ]
