# Generated by Django 3.0.6 on 2020-06-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evangelizacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evangelizacao',
            name='descripion',
            field=models.TextField(blank=True),
        ),
    ]
