# Generated by Django 3.0.6 on 2020-06-28 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evangelizacao', '0002_evangelizacao_descripion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evangelizacao',
            old_name='descripion',
            new_name='description',
        ),
    ]
