# Generated by Django 3.0.6 on 2020-07-23 18:10

from django.db import migrations, models
import evangelizacao.validators


class Migration(migrations.Migration):

    dependencies = [
        ('evangelizacao', '0003_auto_20200628_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evangelizacao',
            name='doc_file',
            field=models.FileField(upload_to='uploads/evangelizacao/%Y_%m_%d/', validators=[evangelizacao.validators.validate_file_extension]),
        ),
    ]
