# Generated by Django 3.0.6 on 2020-08-17 20:30

from django.db import migrations, models
import evangelizacao.validators


class Migration(migrations.Migration):

    dependencies = [
        ('evangelizacao', '0004_auto_20200723_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evangelizacao',
            name='doc_file',
            field=models.FileField(blank=True, upload_to='uploads/evangelizacao/%Y_%m_%d/', validators=[evangelizacao.validators.validate_file_extension]),
        ),
    ]
