# Generated by Django 3.0.6 on 2020-06-11 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voluntarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('program_type', models.CharField(max_length=200)),
                ('program_date', models.DateTimeField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('photo_main', models.ImageField(upload_to='photos/%Y%m%d/')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='voluntarios.Voluntario')),
            ],
        ),
    ]
