# Generated by Django 3.0.6 on 2020-06-12 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0001_initial'),
        ('programacao', '0002_remove_programacao_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Programacao',
            new_name='Programa',
        ),
    ]
