# Generated by Django 3.0.6 on 2020-06-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacao', '0003_auto_20200612_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='language',
            field=models.CharField(default='Portuguese', max_length=200),
        ),
    ]
